[project]
name = "Bank-Size-Central-Bank-Sensitivity"
version = "0.1.0"
description = "Add a short description here"
authors = ["Butch78 <matthewtyleraylward@hotmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = "3.12.0.*"
cookiecutter = "2.4.0.*"
python-dotenv = "1.0.0.*"
pydantic = "2.4.2.*"
